OnlineShop/OnlineShop/Controllers/CartController.cs
using Common;
using Model.Dao;
using Model.EF;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }

            return View(list);
        }

        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status =  true
            });
        }

        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];

            sessionCart.RemoveAll(n => n.Product.ID == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Update(string cartModel)
            {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(n => n.Product.ID == item.Product.ID);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        public ActionResult AddItem (long productId, int quantity)
        {
            var product = new ProductDao().ViewDetail(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(n=>n.Product.ID == productId))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.ID == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //Tạo mới đối tượng CartItem
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
                //Gán vào session
                Session[CartSession] = list;
            }
            else
            {
                //Tạo mới đối tượng CartItem
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quantity;

                var list = new List<CartItem>();
                list.Add(item);

                //Gán vào session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }

        //Thanh toán
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = cart as List<CartItem>;
            }
            return View(list);
        }

        //Thanh toán
        [HttpPost]
        public ActionResult Payment(string shipname, string mobile, string address, string email)
        {
            OnlineShopDbContext db = new OnlineShopDbContext();

            var order = new Order();
            order.CreatedDate = DateTime.Now;
            order.ShipName = shipname;
            order.ShipMobile = mobile;
            order.ShipAddress = address;
            order.ShipEmail = email;

            try
            {
                var id = new OrderDao().Insert(order);
                var cart = Session[CartSession] as List<CartItem>;
                var detailDao = new OrderDetailDao();
                
                decimal total = 0;
                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail();
                    orderDetail.ProductID = item.Product.ID;
                    orderDetail.OrderID = id;
                    
                    orderDetail.Quantity = item.Quantity;
                    orderDetail.Price = item.Product.Price.GetValueOrDefault(0) * item.Quantity;

                    detailDao.Insert(orderDetail);
                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                    //var sl = new ProductDao().UpdateQuantity(orderDetail.ProductID);
                    //sl.Quantity -= item.Quantity;
                    //db.Entry(sl).State = System.Data.Entity.EntityState.Modified;
                    //db.SaveChanges();

                    string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/Client/template/neworder.html"));

                    content = content.Replace("{{CustomerName}}", shipname);
                    content = content.Replace("{{Phone}}", mobile);
                    content = content.Replace("{{Email}}", email);
                    content = content.Replace("{{Address}}", address);
                    content = content.Replace("{{Total}}", total.ToString("N0"));

                    var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                    new MailHelper().SendMail(email, "Đơn hàng mới từ OnlineShop", content);//email cho khách hàng
                    new MailHelper().SendMail(toEmail, "Đơn hàng mới từ OnlineShop", content);//email cho quản trị
                }
                Session[CartSession] = null;
            }
            catch(Exception ex)
            {
                return Redirect("/loi-thanh-toan");
            }
            return Redirect("/hoan-thanh");
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Fail()
        {
            return View();
        }
    }
}

OnlineShop/OnlineShop/Views/Cart/Fail.cshtml
@{
    ViewBag.Title = "Fail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-dismissable">
    Đặt hàng không thành công!
</div>
<button class="btn"><a href="/thanh-toan">Quay lại</a></button>

OnlineShop/OnlineShop/Views/Cart/Index.cshtml
@model List<OnlineShop.Models.CartItem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section jsFooter{
    <script src="/Assets/Client/js/controller/cartController.js"></script>
}
<div class="content">

    <div class="section group">
        @if (Model.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã SP</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Product.ID</td>
                            <td>@item.Product.Name</td>
                            <td><img src="@item.Product.Image" width="100" /></td>
                            <td><input type="number" min="1" class="txtQuantity" data-id="@item.Product.ID" value="@item.Quantity" /></td>
                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
                            <td><a href="#" data-id="@item.Product.ID" class="btn-delete">Xoá</a></td>
                        </tr>
                    }
                </tbody>
            </table>

            <button id="btnContinue" class="btn">Tiếp tục mua hàng</button>
            <button id="btnUpdate" class="btn">Cập nhật giỏ hàng</button>
            <button id="btnDeleteAll" class="btn">Xoá giỏ hàng</button>
            <button id="btnPayment" class="btn">Thanh toán</button>
        }
        else
        {
            <span class="alert alert-danger">Chưa có sản phẩm nào trong giỏ hàng</span>
        }

    </div>
</div>

OnlineShop/OnlineShop/Views/Cart/Payment.cshtml
@model List<OnlineShop.Models.CartItem>

@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">

    <div class="section group">
        @if (Model.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã SP</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Product.ID</td>
                            <td>@item.Product.Name</td>
                            <td><img src="@item.Product.Image" width="100" /></td>
                            <td><label class="txtQuantity" data-id="@item.Product.ID">@item.Quantity</label></td>
                            @*<td><input readonly="true" class="txtQuantity" data-id="@item.Product.ID" value="@item.Quantity" /></td>*@
                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
    <div class="section group">
        <div class="col-md-6">
            @using (Html.BeginForm("Payment", "Cart", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Người nhận</label>
                    <input type="text" name="shipname" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Điện thoại</label>
                    <input type="text" name="mobile" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Địa chỉ</label>
                    <input type="text" name="address" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="text" name="email" class="form-control" />
                </div>
                <button type="submit" class="btn btn-danger">Đặt hàng</button>
            }
        </div>
        
    </div>
</div>

OnlineShop/OnlineShop/Views/Cart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-success">
    Đặt hàng thành công!
</div>
<button class="btn"><a href="/Home/Index">Quay lại</a></button>